// automatically generated by the FlatBuffers compiler, do not modify

package run2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClusterPos struct {
	_tab flatbuffers.Table
}

func GetRootAsClusterPos(buf []byte, offset flatbuffers.UOffsetT) *ClusterPos {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClusterPos{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ClusterPos) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClusterPos) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClusterPos) X() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ClusterPos) MutateX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *ClusterPos) Y() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ClusterPos) MutateY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *ClusterPos) Z() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *ClusterPos) MutateZ(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func ClusterPosStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ClusterPosAddX(builder *flatbuffers.Builder, x float32) {
	builder.PrependFloat32Slot(0, x, 0.0)
}
func ClusterPosAddY(builder *flatbuffers.Builder, y float32) {
	builder.PrependFloat32Slot(1, y, 0.0)
}
func ClusterPosAddZ(builder *flatbuffers.Builder, z float32) {
	builder.PrependFloat32Slot(2, z, 0.0)
}
func ClusterPosEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
