// automatically generated by the FlatBuffers compiler, do not modify

package run2

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PreCluster struct {
	_tab flatbuffers.Table
}

func GetRootAsPreCluster(buf []byte, offset flatbuffers.UOffsetT) *PreCluster {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PreCluster{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PreCluster) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PreCluster) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PreCluster) Digits(obj *Digit, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PreCluster) DigitsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PreClusterStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PreClusterAddDigits(builder *flatbuffers.Builder, digits flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(digits), 0)
}
func PreClusterStartDigitsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PreClusterEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
