language: go
go:
  - 1.10.x
  - 1.11.x
  - master
os:
  - linux
  - macosx
matrix:
 fast_finish: true
 allow_failures:
   - go: master


notifications:
  email:
    recipients:
      - laurent.aphecetche@cern.ch
    on_success: change
    on_failure: always
